int32 blinks                    # Number of flashes (1 flash = 1 time on + 1 time off) - duration: long
int32 fast_blinks               # Number of flashes (1 flash = 1 time on + 1 time off) - duration: short (takes place from one long flash to another)

# TODO: put fast_duration_on and off inside a single parameter that is simply split in 2 (similar to the LED stripe) and the information about on/off duration is extracted from there
#float64 fast_duration_on        # These two parameters determine how fast the flashes with short duration are
#float64 fast_duration_off       # in [s] (use 0.0x as values since it looks more like fast flashing)
#float64 pause_between_long_blinks # pause between each set of fast flashes; in [s] or [ms]
#float64 fast_duration          # Determines how fast the flashes with short duration are. Internally this parameter is split into two parts: 3/4 for on and 1/4 for off duration of a signle flash

#######################################################
# The given stripe (start to end) is always devided   #
# in two equal halves. The size of each inner stripe  #
# is determined by the inner_size_ratio               #
#                                                     #
# start-------------------------------------------end #
# left_outer | left_inner | right_inner | right_outer #
#######################################################
# Following two parameters determine the total size of the stripe, which is subdivided in smaller subsections (see comment above)
int32 start_led
int32 end_led

std_msgs/ColorRGBA color_outer
std_msgs/ColorRGBA color_inner

int32 num_inner_leds            # Number of LEDs for EACH inner stripe; it can be <= the half of all LEDs defined by start_led and end_led
---
int32 blinks_left               # Result (if == 0 then really successful); refers to the flashes with LONG duration only
---
int32 fast_blinks_left          # Feedback: number of flashes left until the next flash with long duration
int32 blinks_left               # Feedback: number of flashes left until the goal is completed; refers to the flashes with LONG duration only
