# TODO
std_msgs/ColorRGBA color    # RGB values [0-1] for all LEDs
int32  blinkNumber          # Number of flashes (1 flash = 1 time on + 1 time off)
float32 durationOn          # in [s]
float32 durationOff         # in [s]
int32 start_led
int32 end_led
# TODO - encrypt what Ruben is doing
---
float32 real_duration # in [s]
---
float32 until_end   # in [s]
